### PR TITLE
added animations and some card design changes

### PR DESCRIPTION
**Pull request by Abhijeet03s**
I added animations on the Service page and also added some designs on the cards.

[React-App.webm](https://user-images.githubusercontent.com/107188710/195973339-04cc08b3-a56f-4211-b567-6485366a3ce9.webm)

### CODE REVIEW

**Comment by Adarsh-K21** [comment]
@Abhijeet03s  first kindly fetch the fork in your repo, then "git pull origin main" then git push origin main

**Comment by Adarsh-K21** [comment]
Do follow the readme instructions

**Comment by Abhijeet03s** [comment]
> @Abhijeet03s  first kindly fetch the fork in your repo, then "git pull origin main" then git push origin main

I have already forked the repo. And push the code to the main branch. Are you facing any problems?

**Comment by Abhijeet03s** [comment]
> Do follow the readme instructions

Yes.

**Pull request closed without merging**
